services:
  varnish:
    build:
      context: ./varnish
    container_name: varnish-cache
    ports:
      - "8080:80" # Revertendo para 8080 por simplicidade
    networks:
      - hemlock-test-net
    depends_on:
      app-header-vuln:
        condition: service_healthy
      app-param-vuln:
        condition: service_healthy
      app-deception-vuln:
        condition: service_healthy
      app-control:
        condition: service_healthy

  app-header-vuln:
    build:
      context: ./apps/header-poisoning
    container_name: app-header-vuln
    networks:
      - hemlock-test-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 5s
      timeout: 2s
      retries: 5

  app-param-vuln:
    build:
      context: ./apps/param-poisoning
    container_name: app-param-vuln
    networks:
      - hemlock-test-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002"]
      interval: 5s
      timeout: 2s
      retries: 5

  app-deception-vuln:
    build:
      context: ./apps/deception-vuln
    container_name: app-deception-vuln
    networks:
      - hemlock-test-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003"]
      interval: 5s
      timeout: 2s
      retries: 5

  app-control:
    build:
      context: ./apps/control
    container_name: app-control
    networks:
      - hemlock-test-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004"]
      interval: 5s
      timeout: 2s
      retries: 5

networks:
  hemlock-test-net:
    driver: bridge 